name: Lighthouse CI tests
on: [pull_request, push]

jobs:
  lighthouse:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "2.x"
          architecture: "x64"
      - name: Run lighthouse checks
        run: python -m scripts.run_lighthouse_tests --enable_compression
